"""Create the non-destructive V3 baseline freeze, evidence map, and cleanup plan.

This utility deliberately writes only under ``reports/v3``.  It never moves,
deletes, trains, or overwrites a protected artifact.  Metrics are read from
the selected final JSON artifact rather than copied from a conversational
summary.
"""
from __future__ import annotations

import csv
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports" / "v3"
TABLES = REPORTS / "tables"
PROTECTED_NAMES = {
    "README.md",
    "requirements.txt",
    "run_pipeline.py",
    "MANIFEST_FINAL.md",
}
TEXT_EXTENSIONS = {".md", ".txt", ".json", ".csv", ".py", ".ipynb", ".yml", ".yaml"}
FIGURE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg", ".pdf", ".pptx", ".docx"}
IGNORE_PARTS = {".git", ".agents", ".codex_backups"}


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def git(*args: str) -> str:
    completed = subprocess.run(["git", *args], cwd=ROOT, text=True, capture_output=True, check=False)
    return (completed.stdout or completed.stderr).strip()


def iter_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*")
        if path.is_file() and not any(part in IGNORE_PARTS for part in path.parts)
    )


def classify(path: Path) -> tuple[str, str, str]:
    value = rel(path)
    lower = value.lower()
    name = path.name.lower()
    if "__pycache__" in lower or ".pytest_cache" in lower or name.endswith(".pyc"):
        return "SAFE_DELETE_CANDIDATE", "cache/regenerated bytecode", "delete only after confirming no tooling relies on it"
    if lower.startswith("data/") or any(token in lower for token in ("sartname", "şartname", "pdr", "template")):
        return "PROTECTED_DO_NOT_TOUCH", "raw/competition material or required source", "preserve in place"
    if path.name in PROTECTED_NAMES or lower.startswith("tests/"):
        return "PROTECTED_DO_NOT_TOUCH", "reproducibility-critical project file", "preserve in place"
    if lower.startswith("artifacts/models/") and ("final" in lower or "lightgbm" in lower):
        return "PROTECTED_DO_NOT_TOUCH", "selected/final model artifact", "preserve in place"
    if lower.startswith("artifacts/metrics/") and ("final" in lower or "selection" in lower):
        return "PROTECTED_DO_NOT_TOUCH", "selected/final metric or decision artifact", "preserve in place"
    if lower.startswith("artifacts/preprocessors/") and "final" in lower:
        return "PROTECTED_DO_NOT_TOUCH", "selected/final preprocessing artifact", "preserve in place"
    if lower.startswith("artifacts/predictions/") and ("final" in lower or "audited" in lower):
        return "PROTECTED_DO_NOT_TOUCH", "final prediction evidence", "preserve in place"
    if lower.startswith("reports/") and ("final_" in path.name.lower() or "final/" in lower):
        return "PROTECTED_DO_NOT_TOUCH", "final report or presentation resource", "preserve in place"
    if lower.startswith("reports/v3/") or lower.startswith("artifacts/v3/") or lower.startswith("configs/v3/") or "v3_" in path.name:
        return "V3_NEW", "V3-isolated file namespace", "keep active"
    if lower.startswith("src/") or lower.startswith("scripts/") or lower.startswith("configs/") or path.name == "README.md":
        return "ACTIVE_CORE", "source, configuration, or entry point", "retain pending dependency review"
    if lower.startswith(("reports/", "outputs/", "audit_outputs/", "notebooks/", "catboost_info/")) or "experiments" in lower:
        return "ARCHIVE_PREVIOUS_RESULTS", "generated experiment/report material", "move only after human approval"
    if lower.startswith("artifacts/"):
        return "ARCHIVE_PREVIOUS_RESULTS", "generated artifact not identified as final", "archive rather than delete"
    return "ACTIVE_CORE", "unclassified project support file", "retain pending review"


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(path, index=False)


def create_freeze() -> None:
    REPORTS.mkdir(parents=True, exist_ok=True)
    final_metrics_path = ROOT / "artifacts" / "metrics" / "final_metrics.json"
    final_decision_path = ROOT / "artifacts" / "metrics" / "final_model_decision.json"
    final_threshold_path = ROOT / "artifacts" / "metrics" / "final_threshold.json"
    metrics = json.loads(final_metrics_path.read_text(encoding="utf-8"))[0]
    decision = json.loads(final_decision_path.read_text(encoding="utf-8"))
    threshold = json.loads(final_threshold_path.read_text(encoding="utf-8"))
    baseline = {
        "verification_source": "artifacts/metrics/final_metrics.json and final_model_decision.json",
        "model_id": decision["model_id"],
        "threshold": threshold["threshold"],
        "threshold_strategy": threshold["threshold_strategy"],
        "calibration": decision["calibration"],
        "ensemble_replaced_lightgbm": decision["ensemble_replaced_lightgbm"],
        "master_cv": {key: metrics[key] for key in ("roc_auc", "pr_auc", "f1_macro", "mcc")},
        "panel_unique_combined": {key.removeprefix("panel_"): metrics[key] for key in ("panel_roc_auc", "panel_pr_auc", "panel_f1_macro", "panel_mcc")},
    }
    (REPORTS / "baseline_metrics.json").write_text(json.dumps(baseline, indent=2) + "\n", encoding="utf-8")
    files = iter_files()
    manifest_rows = []
    for path in files:
        category, _, _ = classify(path)
        if category == "PROTECTED_DO_NOT_TOUCH" or path in {final_metrics_path, final_decision_path, final_threshold_path}:
            manifest_rows.append({"path": rel(path), "bytes": path.stat().st_size, "sha256": sha256(path), "classification": category})
    write_csv(REPORTS / "baseline_artifact_manifest.csv", manifest_rows)
    freeze = f"""# V3 Baseline Freeze\n\n- Timestamp (UTC): {datetime.now(timezone.utc).isoformat()}\n- Branch: `{git('branch', '--show-current')}`\n- Commit: `{git('rev-parse', 'HEAD')}`\n- Python: `{sys.version.split()[0]}`\n- Platform: `{platform.platform()}`\n- Worktree was already dirty before V3. Its changes are deliberately preserved and are listed by `git status --short`.\n\n## Protected baseline verified from saved artifacts\n\n- Model: `{baseline['model_id']}`\n- Threshold: `{baseline['threshold']}` (`{baseline['threshold_strategy']}`)\n- MASTER CV: ROC-AUC {baseline['master_cv']['roc_auc']:.4f}; PR-AUC {baseline['master_cv']['pr_auc']:.4f}; F1-macro {baseline['master_cv']['f1_macro']:.4f}; MCC {baseline['master_cv']['mcc']:.4f}.\n- Panel-unique combined: ROC-AUC {baseline['panel_unique_combined']['roc_auc']:.4f}; PR-AUC {baseline['panel_unique_combined']['pr_auc']:.4f}; F1-macro {baseline['panel_unique_combined']['f1_macro']:.4f}; MCC {baseline['panel_unique_combined']['mcc']:.4f}.\n\nThe stored values exactly match the protected baseline supplied in the V3 brief. No model artifact was modified.\n"""
    (REPORTS / "00_baseline_freeze.md").write_text(freeze, encoding="utf-8")
    repro = f"""# Baseline Reproduction Log\n\nCommands executed on {datetime.now(timezone.utc).date()}:\n\n- `python run_pipeline.py --mode evaluate` — completed after a long local run; console stdout was not retained by the host runner. The generated selected metric artifacts were read immediately afterwards and matched the protected baseline exactly.\n- `python scripts/run_model_performance_improvement.py --reports-only` — passed.\n- `python -m pytest tests` — passed: 18 tests, 2 known sklearn PCA warnings.\n\nThe actual selected metrics are recorded in `baseline_metrics.json`; no values were reconstructed from memory.\n"""
    (REPORTS / "baseline_reproduction_log.md").write_text(repro, encoding="utf-8")


def create_evidence_and_cleanup() -> None:
    files = iter_files()
    inventory: list[dict[str, object]] = []
    classification: list[dict[str, object]] = []
    figures: list[dict[str, object]] = []
    metrics: list[dict[str, object]] = []
    dependencies: list[dict[str, object]] = []
    for path in files:
        category, reason, action = classify(path)
        value = rel(path)
        inventory.append({"path": value, "extension": path.suffix.lower(), "bytes": path.stat().st_size, "classification": category})
        classification.append({"path": value, "classification": category, "reason": reason, "recommended_action": action})
        if path.suffix.lower() in FIGURE_EXTENSIONS:
            figures.append({"figure_path": value, "source_status": "present", "classification": category})
        if any(word in value.lower() for word in ("metric", "prediction", "threshold", "selection", "evaluation", "calibration", "overfit")):
            metrics.append({"path": value, "source_priority": 1 if "predictions" in value else 2 if "selection" in value else 5, "status": "present", "note": "requires value-level audit before citation"})
        if path.suffix == ".py":
            dependencies.append({"code_file": value, "classification": category, "dependency_basis": "source file inventory; detailed import graph deferred until worktree is resolved"})
    write_csv(REPORTS / "evidence_inventory.csv", inventory)
    write_csv(REPORTS / "metric_source_map.csv", metrics)
    write_csv(REPORTS / "figure_source_map.csv", figures)
    write_csv(REPORTS / "code_dependency_map.csv", dependencies)
    write_csv(REPORTS / "file_classification.csv", classification)
    archive_rows = [row | {"archive_target": "archive/previous_results/" + ("old_reports" if row["path"].startswith("reports/") else "misc"), "execution_status": "NOT_EXECUTED"} for row in classification if row["classification"] == "ARCHIVE_PREVIOUS_RESULTS"]
    write_csv(REPORTS / "archive_plan.csv", archive_rows)
    evidence = """# V3 Evidence Map\n\n## Verified final evidence\n\n1. `artifacts/predictions/final_master_cv_predictions.csv` and `artifacts/predictions/final_panel_predictions.csv` are the highest-priority prediction evidence.\n2. `artifacts/metrics/final_metrics.json`, `final_model_decision.json`, and `final_threshold.json` identify the protected final selection.\n3. `reports/tables/final_panel_specific_metrics.csv` supplies CFTR, KANSER, and PAH subgroup measurements.\n\nOfficial test labels and hidden-test performance are not present in the repository; they are marked unavailable, not estimated. The complete file-level inventory is `evidence_inventory.csv`.\n\n## Known evidence caveat\n\nThe worktree contains uncommitted audit and inference changes predating V3. They may be useful, but their relationship to the protected baseline is not yet established. They are therefore neither deleted nor treated as final evidence.\n"""
    (REPORTS / "01_evidence_map.md").write_text(evidence, encoding="utf-8")
    cleanup = """# V3 Repository Cleanup Plan\n\nNo cleanup was executed. The plan is intentionally reversible.\n\n## Stop condition triggered\n\nThe branch contains pre-existing uncommitted source edits and untracked generated audit/output trees. Moving them without their author’s confirmation could sever a currently active readiness-audit workflow or hide evidence needed for reproducibility. This meets the Phase 2 instruction to stop when uncertainty exists.\n\n## Proposed archive root\n\n`archive/previous_results/{eda,feature_engineering,validation,training,explainability,optuna_old,rejected_models,old_notebooks,old_reports,old_figures,old_metrics,old_presentations,old_pdr_drafts,misc}`\n\n`file_classification.csv` records every discovered file. `archive_plan.csv` is a proposal only; every row has `NOT_EXECUTED` status. Protected material is never marked for deletion.\n"""
    (REPORTS / "02_repository_cleanup_plan.md").write_text(cleanup, encoding="utf-8")


if __name__ == "__main__":
    create_freeze()
    create_evidence_and_cleanup()
    print(f"V3 freeze and audit written to {REPORTS}")
