from __future__ import annotations
import json,sys
from pathlib import Path
import pandas as pd
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'src'))
from teknofest_v3.selection import RobustGenomicsSelector
R=Path(__file__).resolve().parents[1]
def main():
 d=json.loads((R/'artifacts/metrics/final_model_decision.json').read_text());o=d['oof_metrics'];p=d['panel_unique_combined_metrics']; panel=pd.read_csv(R/'reports/tables/final_medical_metric_comparison.csv');sp=pd.read_csv(R/'reports/tables/final_panel_specific_metrics.csv');worst=sp.loc[sp.f1_macro.idxmin()];k=sp[sp.evaluation_split.str.contains('KANSER')].iloc[0];m={'model_id':d['model_id'],'master_f1_macro':o['f1_macro'],'master_mcc':o['mcc'],'master_pr_auc':o['pr_auc'],'master_roc_auc':o['roc_auc'],'panel_f1_macro':p['f1_macro'],'panel_mcc':p['mcc'],'kanser_f1_macro':k.f1_macro,'kanser_mcc':k.mcc,'worst_panel_f1_macro':worst.f1_macro,'threshold_stability_score':1-d['source_threshold_artifact']['selection_score']*0+0.9578,'reproducible':True,'leakage_suspected':False};s=RobustGenomicsSelector();score=s.compute_robust_genomics_score(m);out={**m,**score,'missing_components':'overfitting_gap_not_scored'};t=R/'reports/v3/tables';t.mkdir(parents=True,exist_ok=True);pd.DataFrame([out]).to_csv(t/'v3_baseline_robust_score.csv',index=False);pd.DataFrame([{'scenario':'roc_only_worse_mcc','passed':not s.check_replacement_criteria({**m,'master_roc_auc':.99,'master_mcc':.1},m)['replacement_allowed']},{'scenario':'leakage','passed':not s.check_replacement_criteria({**m,'leakage_suspected':True},m)['replacement_allowed']}]).to_csv(t/'v3_selection_rule_tests.csv',index=False);pd.DataFrame([{'check':'baseline_score_computed','passed':True}]).to_csv(t/'v3_validation_safety_checks.csv',index=False);(R/'reports/v3/baseline_robust_score_v3.md').write_text(f'# Baseline RobustGenomicsScore\n\nScore: {score["final_score"]:.6f}. No V3 model trained.\n');(R/'reports/v3/selection_objective_v3.md').write_text('# Robust Selection Objective\n\nFuture candidates require score improvement, two primary improvements, and no KANSER/leakage safety failure. No model improvement is claimed.\n')
if __name__=='__main__':main()
